/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testing;


import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;



import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;























/**
 *
 * @author DELL
 */
public class Admin_blog extends javax.swing.JFrame {

    Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
    private JFrame frame;
    public Admin_blog() {
        initComponents();
         jScrollPane5.setOpaque(false);
        jScrollPane5.getViewport().setOpaque(false);
        jScrollPane5.setBorder(null);
        jScrollPane5.setViewportBorder(null);
         jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    //============================================show table function =============================
     public final void showTableData(){

try{

con = DriverManager.getConnection("jdbc:mysql://localhost/articles","root","1234567890");
String sql = "SELECT * FROM articles";
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
jTable1.setModel(DbUtils.resultSetToTableModel(rs));//The DbUtils.resultSetToTableModel(rs) method presumably retrieves the data
                                                             // from the ResultSet (rs) and converts it into a format that can be easily displayed within the JTable.
}

catch(SQLException ex){
JOptionPane.showMessageDialog(null, ex);
}

}
   
 //=================================================function end====================================   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new scrollbar.ScrollPaneWin11();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        image = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArticleNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ArticleTypeBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        btnReset = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        btenExit = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        btnDelete = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        btnUpdate = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnAdd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        selectimage = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTitle = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        kGradientPanel6.setkGradientFocus(1000);
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 153, 255));
        kGradientPanel6.setMinimumSize(new java.awt.Dimension(1300, 1300));
        kGradientPanel6.setPreferredSize(new java.awt.Dimension(1300, 1300));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateChooser.setBackground(new java.awt.Color(255, 255, 255));
        dateChooser.setDateFormatString("yyyy-MM-dd");
        kGradientPanel6.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 197, 32));

        image.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        kGradientPanel6.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 220, 140));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Publish Date  :");
        kGradientPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, 30));

        txtArticleNo.setBackground(new java.awt.Color(255, 255, 255));
        txtArticleNo.setFont(new java.awt.Font("Thunder", 0, 21)); // NOI18N
        txtArticleNo.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel6.add(txtArticleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 91, 30));

        jLabel4.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Article No.");
        kGradientPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 30));

        jLabel2.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type  :");
        kGradientPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 70, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Title:");
        kGradientPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        ArticleTypeBox.setBackground(new java.awt.Color(255, 255, 255));
        ArticleTypeBox.setFont(new java.awt.Font("Thunder", 0, 21)); // NOI18N
        ArticleTypeBox.setForeground(new java.awt.Color(0, 0, 0));
        ArticleTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "blog", "news", " " }));
        ArticleTypeBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 153, 255)));
        kGradientPanel6.add(ArticleTypeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, 40));

        jLabel1.setFont(new java.awt.Font("The Bold Font", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Article Details");
        kGradientPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr no", "type", "publsih date", "Title", "description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 830, 750, -1));

        kGradientPanel3.setFont(new java.awt.Font("The Bold Font", 0, 12)); // NOI18N
        kGradientPanel3.setkStartColor(new java.awt.Color(102, 204, 255));

        btnReset.setFont(new java.awt.Font("The Bold Font", 1, 24)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReset.setText("RESET");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel6.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 1020, -1, -1));

        kGradientPanel5.setFont(new java.awt.Font("The Bold Font", 0, 12)); // NOI18N
        kGradientPanel5.setkStartColor(new java.awt.Color(102, 204, 255));

        btenExit.setFont(new java.awt.Font("The Bold Font", 1, 24)); // NOI18N
        btenExit.setForeground(new java.awt.Color(255, 255, 255));
        btenExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btenExit.setText("EXIT");
        btenExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btenExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btenExit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btenExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel6.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 1190, -1, -1));

        kGradientPanel4.setFont(new java.awt.Font("The Bold Font", 0, 12)); // NOI18N
        kGradientPanel4.setkStartColor(new java.awt.Color(102, 204, 255));

        btnDelete.setFont(new java.awt.Font("The Bold Font", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setText("DELETE");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        kGradientPanel6.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 930, 220, 60));

        kGradientPanel2.setFont(new java.awt.Font("The Bold Font", 0, 12)); // NOI18N
        kGradientPanel2.setkStartColor(new java.awt.Color(102, 204, 255));

        btnUpdate.setFont(new java.awt.Font("The Bold Font", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdate.setText("UPDATE");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel6.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 1110, 220, -1));

        kGradientPanel1.setFont(new java.awt.Font("The Bold Font", 0, 12)); // NOI18N
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 204, 255));

        btnAdd.setFont(new java.awt.Font("The Bold Font", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel6.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 850, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-button-85.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        kGradientPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 160, 170));

        kGradientPanel12.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel12.setkStartColor(new java.awt.Color(51, 153, 255));

        selectimage.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        selectimage.setForeground(new java.awt.Color(255, 255, 255));
        selectimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectimage.setText("select image");
        selectimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectimageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel12Layout = new javax.swing.GroupLayout(kGradientPanel12);
        kGradientPanel12.setLayout(kGradientPanel12Layout);
        kGradientPanel12Layout.setHorizontalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addComponent(selectimage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel12Layout.setVerticalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(selectimage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel6.add(kGradientPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 750, 150, 50));

        address1.setBackground(new java.awt.Color(255, 255, 255));
        address1.setFont(new java.awt.Font("Thunder", 0, 21)); // NOI18N
        address1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel6.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 750, 390, 50));

        jLabel11.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Description  :");
        kGradientPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, 90));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        txtDescription.setBackground(new java.awt.Color(255, 255, 255));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Thunder", 0, 21)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(0, 0, 0));
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDescription);

        kGradientPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 650, 200));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        txtTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtTitle.setColumns(20);
        txtTitle.setFont(new java.awt.Font("Thunder", 0, 21)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 0, 0));
        txtTitle.setRows(5);
        jScrollPane4.setViewportView(txtTitle);

        kGradientPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 390, 50));

        jScrollPane5.setViewportView(kGradientPanel6);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 940));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

     
             try {
            // TODO add your handling code here:
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();//provides the underlying data model for a JTable component. It holds the data that is displayed within the JTable. 
                                                                                     // Constructs a DefaultTableModel with rowCount and columnCount of null object values.
            int SelectedRows = jTable1.getSelectedRow();//is used to determine which row is currently selected by the user.
            
                
            
            
            String Type = RecordTable.getValueAt(SelectedRows, 1).toString();//getvaluedat is used to retrieve the value located at a specific cell in the table.
                          switch(Type)
                          {
                              case "blog" -> ArticleTypeBox.setSelectedIndex(1);
                                  
                               case "news" -> ArticleTypeBox.setSelectedIndex(2);    
                          }
            
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)RecordTable.getValueAt(SelectedRows, 2));//converting to suitable format
            dateChooser.setDate(date);
            txtTitle.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
            txtDescription.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
            txtArticleNo.setText((String) RecordTable.getValueAt(SelectedRows, 0));
            
            
            
            
           
            
        } 
        catch (ParseException ex)
        {
            Logger.getLogger(Admin_blog.class.getName()).log(Level.SEVERE, null, ex);
        }
       

       

    }//GEN-LAST:event_jTable1MouseClicked
    File f = null;
    String path = null;
    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
         try{

String sql = "INSERT INTO articles (Type, Date,Title,Description,photo)VALUES (?,?,?,?,?)";

con = DriverManager.getConnection("jdbc:mysql://localhost/articles","root","1234567890");

pst = con.prepareStatement(sql);

         String Article_type;
         Article_type= ArticleTypeBox.getSelectedItem().toString();
         pst.setString(1, Article_type);
         
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         String date = sdf.format(dateChooser.getDate());
         pst.setString(2, date);

pst.setString(3,txtTitle.getText());

pst.setString(4,txtDescription.getText());
InputStream is = new FileInputStream(f);/*It is used for reading binary data from the file
                                                     A FileInputStream is a subclass of InputStream specifically designed for reading binary data from a file.
                                                       It's used to reference the file you want to open for reading.*/

pst.setBlob(5, is);

image.setIcon(new ImageIcon()); /*The setIcon method is used to set the icon or image that will be displayed by the component.
                                      new ImageIcon(): This part of the code creates a new ImageIcon object using the default constructor 
                                     new ImageIcon(). An ImageIcon is a class in Java that represents an image or icon that can be displayed 
                                     within graphical components. The default constructor creates an empty ImageIcon object with no image data.*/

pst.executeUpdate();

JOptionPane.showMessageDialog(null, "inserted successfully");

 

}

catch(SQLException | HeadlessException ex){

JOptionPane.showMessageDialog(null, ex);

}       catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_blog.class.getName()).log(Level.SEVERE, null, ex);
        }
//AutoIncrement();
showTableData();
       
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
         try{

String sql = "DELETE FROM articles WHERE Title =?";

con = DriverManager.getConnection("jdbc:mysql://localhost/articles","root","1234567890");

pst = con.prepareStatement(sql);

pst.setString(1,txtTitle.getText());

pst.executeUpdate();

JOptionPane.showMessageDialog(null, "delete successfully");

 

}

catch(SQLException | HeadlessException ex){

JOptionPane.showMessageDialog(null, ex);

}
//AutoIncrement();
showTableData();

       
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
         try{

 String sql = "UPDATE articles SET Type=?,Date=?,Title=?,Description=?, photo = ? WHERE SrNo=?";

 con = DriverManager.getConnection("jdbc:mysql://localhost/articles","root","1234567890");

 pst = con.prepareStatement(sql);

 pst.setString(6, txtArticleNo.getText());

 String Article_type;
         Article_type= ArticleTypeBox.getSelectedItem().toString();
         pst.setString(1, Article_type);
         
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         String date = sdf.format(dateChooser.getDate());
         pst.setString(2, date);

pst.setString(3,txtTitle.getText());

pst.setString(4,txtDescription.getText());

InputStream is = new FileInputStream(f);

pst.setBlob(5, is);





 pst.executeUpdate();

 JOptionPane.showMessageDialog(null, "updated successfully");

 }

 catch(SQLException | HeadlessException ex){

 JOptionPane.showMessageDialog(null, ex);

 }      catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_blog.class.getName()).log(Level.SEVERE, null, ex);
        }
        showTableData();
      
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:

        ArticleTypeBox.setSelectedIndex(0);
        dateChooser.setCalendar(null);
        txtTitle.setText("");
        txtDescription.setText("");
        address1.setText("");
    }//GEN-LAST:event_btnResetMouseClicked

    private void btenExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btenExitMouseClicked
        // TODO add your handling code here:
         frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "confirm if you want to exit",
            "mysql connector",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    {
        System.exit(0);
        }
    }//GEN-LAST:event_btenExitMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        admin_page ap = new admin_page();
        ap.show();
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
    
    
    
    
    
    private void selectimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectimageMouseClicked
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter fnf = new FileNameExtensionFilter("PNG JPG AND JPEG","jpg","png","jpeg");
        chooser.addChoosableFileFilter(fnf);                          /*FileNameExtensionFilter is a class that represents a file filter. It allows you
                                                                        to specify a set of file extensions and a description for those extensions.*/
        int load; //showOpenDialog() is used to open a dialog box.
        load = chooser.showOpenDialog(null);

        if(load == chooser.APPROVE_OPTION){
            f = chooser.getSelectedFile();
            path = f.getAbsolutePath();
            address1.setText(path);
            ImageIcon i2 = new ImageIcon(path);
            Image img1 = i2.getImage().getScaledInstance(220, 140, Image.SCALE_SMOOTH);
            image.setIcon(new ImageIcon(img1));
        }
    }//GEN-LAST:event_selectimageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_blog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_blog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_blog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_blog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_blog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ArticleTypeBox;
    private javax.swing.JTextField address1;
    private javax.swing.JLabel btenExit;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnUpdate;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JLabel selectimage;
    private javax.swing.JTextField txtArticleNo;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtTitle;
    // End of variables declaration//GEN-END:variables
}
