/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sem3miniproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JPanel;

/**
 *
 * @author shigvan
 */
public class PAGE13 extends javax.swing.JFrame {

    /**
     * Creates new form exp1
     */
    public PAGE13() {
        initComponents();
         try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "purv@&soh@m9222");
            String username = jLabel2.getText();

            if (username.length() > 0) {
                String personalSql = "select * from personal where username = '" + username + "'";
                String educationSql = "select * from education where username = '" + username + "'";
                String sipSql = "select * from sip where username = '" + username + "'";
                 String wecSql = "select * from wec where username = '" + username + "'";

                Statement personalStm = conn.createStatement();
                Statement educationStm = conn.createStatement();
                Statement sipStm = conn.createStatement();
                 Statement wecStm = conn.createStatement();

                java.sql.ResultSet personalRs = personalStm.executeQuery(personalSql);
                java.sql.ResultSet educationRs = educationStm.executeQuery(educationSql);
                java.sql.ResultSet sipRs = sipStm.executeQuery(sipSql);
                java.sql.ResultSet wecRs = wecStm.executeQuery(wecSql);

                if (personalRs.next()) {
                    String email = personalRs.getString(3);
                    jLabel3.setText(email);
                    String contact = personalRs.getString(4);
                    jLabel4.setText(contact);
                    String country = personalRs.getString(5);
                    jLabel5.setText(country);
                    String links = personalRs.getString(7);
                    jLabel6.setText(links);
                    String summary = personalRs.getString(8);
                    jLabel8.setText(summary);
                }

                if (educationRs.next()) {
                    String education = educationRs.getString(2);
                    jLabel7.setText(education);
                    
                } 
                
                if (wecRs.next()) {
                    String certificate = wecRs.getString(4);
                    jTextArea4.setText(certificate);
                    
                } 
                
                if (sipRs.next()) {
                        String projects = sipRs.getString(4);
                        jLabel9.setText(projects);
                        String skills = sipRs.getString(2);
                        jLabel8.setText(skills);
                    } 
                else {
                        javax.swing.JOptionPane.showMessageDialog(this, "No projects data found.");
                    }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Credentials");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 210, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 210, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 210, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 110, -1));

        jLabel7.setText("jLabel7");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel9");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 210, 20));

        jTextArea5.setBackground(new java.awt.Color(56, 182, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 250, 380));

        jTextArea4.setBackground(new java.awt.Color(56, 182, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 260, 280));

        jTextArea3.setBackground(new java.awt.Color(56, 182, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 260, 310));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(56, 182, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 250, 270));

        jTextArea2.setBackground(new java.awt.Color(56, 182, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 250, 260));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sem3miniproject/DES 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 850, -1));

        jLabel2.setText("Ayush23");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("click here to preview your resume let's go");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 450, 50));

        jButton1.setText("PREVIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 90, 30));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 50));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "purv@&soh@m9222");
            String username = jLabel2.getText();

            if (username.length() > 0) {
                String personalSql = "select * from personal where username = '" + username + "'";
                String educationSql = "select * from education where username = '" + username + "'";
                String sipSql = "select * from sip where username = '" + username + "'";
                String wecSql = "select * from wec where username = '" + username + "'";

                Statement personalStm = conn.createStatement();
                Statement educationStm = conn.createStatement();
                Statement sipStm = conn.createStatement();
                Statement wecStm = conn.createStatement();

                java.sql.ResultSet personalRs = personalStm.executeQuery(personalSql);
                java.sql.ResultSet educationRs = educationStm.executeQuery(educationSql);
                java.sql.ResultSet sipRs = sipStm.executeQuery(sipSql);
                java.sql.ResultSet wecRs = wecStm.executeQuery(wecSql);

                if (personalRs.next()) {
                    String fullname = personalRs.getString(3);
                    jLabel12.setText(fullname);
                    String jobp = personalRs.getString(2);
                    jLabel13.setText(jobp);
                    String email = personalRs.getString(4);
                    jLabel3.setText(email);
                    String contact = personalRs.getString(5);
                    jLabel4.setText(contact);
                    String country = personalRs.getString(6);
                    jLabel5.setText(country);
                    String links = personalRs.getString(8);
                    jLabel6.setText(links);
                    String summary = personalRs.getString(9);
                    jTextArea2.setText(summary);

                }

                if (educationRs.next()) {
                    String school = educationRs.getString(2);
                    jLabel7.setText(school);
                    String year = educationRs.getString(3);
                    jLabel8.setText(year);
                    String degree = educationRs.getString(4);
                    jLabel9.setText(degree);
                    

                }

                if (wecRs.next()) {
                    String certificate = wecRs.getString(4);
                    jTextArea4.setText(certificate);
                    String expe = wecRs.getString(3);
                    jTextArea5.setText(expe);

                }

                if (sipRs.next()) {
                    String projects = sipRs.getString(4);
                    jTextArea1.setText(projects);
                    String skills = sipRs.getString(2);
                    jTextArea3.setText(skills);
                }
                else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No projects data found.");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Credentials");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PAGE8 PAGE8Frame = new PAGE8();

        PAGE8Frame.setVisible(true);
        PAGE8Frame.pack();

        PAGE8Frame.setLocationRelativeTo(PAGE8Frame);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       PAGE8 PAGE8Frame = new PAGE8();
        String username= jLabel2.getText();
        PAGE8Frame.setVisible(true);
        PAGE8Frame.pack();
        PAGE8Frame.jLabel15.setText(username);
        PAGE8Frame.setLocationRelativeTo(PAGE8Frame);
        this.dispose();    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAGE13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAGE13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAGE13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAGE13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAGE13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
